"""Project configuration constants."""

MARKET_LOW_PB = 2.0
MARKET_EXTREME_PB = 1.6
MARKET_RISK_PE = 46.0
TOTAL_UNITS = 150
EXTREME_BOTTOM_MONTHLY_UNIT_CAP = 40
CENTER_REBALANCE_PERCENTILE_LOW = 45.0
CENTER_REBALANCE_PERCENTILE_HIGH = 55.0
CENTER_REBALANCE_EQUITY_MIN = 40.0
CENTER_REBALANCE_EQUITY_MAX = 45.0
LOW_PERCENTILE_THRESHOLD = 35.0
GOLDEN_THRESHOLD = 20.0
DIAMOND_THRESHOLD = 10.0
RISK_THRESHOLD = 80.0
ROTATION_PERCENTILE_GAP = 20.0
